apiVersion: v1
kind: Pod
metadata:
  name: simple-app
spec:
  containers:
  - name: server-web
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: green
